#!/bin/sh

set -e

build="tmp"
src="./taglib"
sdk="/opt/wasi-sdk"

cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DWASM=ON \
    -DWITH_ZLIB=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DVISIBILITY_HIDDEN=ON \
    -DBUILD_TESTING=OFF \
    -DWASI_SDK_PREFIX="$sdk" \
    -DCMAKE_TOOLCHAIN_FILE="$sdk"/share/cmake/wasi-sdk.cmake \
    -B "$build" \
    "$src"

cmake \
    --build "$build/bindings/c/" \
    --target tag_c_wasm

mv "$build/bindings/c/tag_c_wasm.wasm" tag_c.wasm

wasm-opt --strip -c -O3 tag_c.wasm -o tag_c.wasm
